### ISSUE TITLE
Host application on external server, to see it from anywhere

### ISSUE THREAD

**Issue by fescalona4** [fescalona4/musicBox#12]

**Comment by jdiaz** [comment]
We should use ![heroku](https://www.heroku.com/) for now.

**Comment by fescalona4** [comment]
app is now deployed in heroku
https://cubanmusicbox.herokuapp.com

**Comment by jdiaz** [comment]
Wow, i'm impressed!

**Comment by fescalona4** [comment]
we need to find a way to put the music somewhere in the cloud, right now is in local, if we put in some google drive or dropbox, not sure how we can stream

**Comment by jdiaz** [comment]
Postgresql or MongoDB
