### ISSUE TITLE
Create music metadata microservice

### ISSUE THREAD

**Issue by jdiaz** [fescalona4/musicBox#15]
Create music metadata store microservice. That is to say, this issue represents the development of a backend service for storing metadata related to all music plays. This includes: play count, most listened, rank (stars), song meta-data e.g. album etc.

**Comment by fescalona4** [comment]
added some comments to existing services

**Comment by jdiaz** [comment]
![architecture](https://cloud.githubusercontent.com/assets/5333759/11609061/f4258384-9b51-11e5-9aa3-87f47e3245bd.png)

**Comment by jdiaz** [comment]
API Gateway is basically and interface or an "aggregator service" between the rest of the services. This will allow us be flexible when adding functionality to the site.

**Comment by jdiaz** [comment]
https://github.com/j-diaz/song-data
